enum actionTypes {
  CHANGE_FILTER = 'CHANGE_FILTER',
  CHANGE_SORT = 'CHANGE_SORT',
  GET_FLIGHTS_START = 'GET_ID_START',
  GET_FLIGHTS_SUCCESS = 'GET_ID_SUCCESS',
  GET_FLIGHTS_ERROR = 'GET_ID_ERROR',
}

export default actionTypes;
